### ISSUE TITLE
Don't create entries for unconfirmed calendar entries

### ISSUE THREAD

**Issue by hannesgassert** [metaodi/cabdriver#11]
Currently calendar entries that are on "maybe" generate taxi lines as well, which I then have to remove. Don't create such lines, or just add them as comments, in case people just forgot to confirm the calendar entries.

**Comment by metaodi** [comment]
@hannesgassert Fixed, please update to 0.0.6. The declined and tentatively accepted entries are now added as a comment.

**Comment by hannesgassert** [comment]
Thanks a bunch!
